version: "3"
services:
  db:
    image: "postgres:9.5.10"
    container_name: "elixir_bootcamp_psql"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data