version: "3"
services:
  db:
    image: "postgres:9.5.10"
    container_name: "erlang_api_db"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=erlang_api
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data